[toolchain]
channel = "1.69"
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl"
]
components = [
    "rustfmt", "clippy"
]
profile = "minimal"